### PR TITLE
no spaces before function parens ()

### PR DESCRIPTION
**Pull request by tdumitrescu**
I know it has been a point of controversy in the past, but we seem to have converged on doing neither `function foo ()` nor `foo = function () {}` so let's enforce consistency.

Also tried out some new formatting to make the rule list more visually parsable:
- replaced 2 / 1 with 'error' / 'warn'
- split warnings and errors into different sections
- column-aligned rule definitions

Get your bikeshed brushes ready! Mainly I care about the first of these.

### CODE REVIEW

**Review by ilyakamens — APPROVED** [review]
🙂

**Review by jordanmnunez — APPROVED** [review]
woow, with formatting

**Comment by zakj** [comment]
+1 on the rule, int to string, single-line rules. -0 on alignment because of diff spillage

**Comment by tdumitrescu** [comment]
-0 is good enough for me! We can revise if diff cruft gets explosive. This repo is pretty low-vol.

**Comment by zakj** [comment]
👍

**Pull request merged**
